import type { UpgradeDefinition } from '../types/game'

export const UPGRADE_DEFINITIONS: UpgradeDefinition[] = [
  {
    id: 'mechanical-keyboard',
    name: 'メカニカルキーボード',
    description: '1レベルごとにタイプ効率+1',
    baseCost: 200,
    costMultiplier: 1.5,
    bonusPerLevel: 1,
    icon: '⌨️',
  },
  {
    id: 'ergonomic-desk',
    name: 'エルゴノミクスデスク',
    description: '1レベルごとにタイプ効率+3',
    baseCost: 2000,
    costMultiplier: 1.6,
    bonusPerLevel: 3,
    icon: '🪑',
  },
  {
    id: 'dual-monitor',
    name: 'デュアルモニター',
    description: '1レベルごとにタイプ効率+8',
    baseCost: 20000,
    costMultiplier: 1.7,
    bonusPerLevel: 8,
    icon: '🖥️',
  },
  {
    id: 'ai-assistant',
    name: 'AIアシスタント',
    description: '1レベルごとにタイプ効率+20',
    baseCost: 200000,
    costMultiplier: 1.8,
    bonusPerLevel: 20,
    icon: '🤖',
  },
  {
    id: 'quantum-keyboard',
    name: '量子キーボード',
    description: '1レベルごとにタイプ効率+50',
    baseCost: 5000000,
    costMultiplier: 1.9,
    bonusPerLevel: 50,
    icon: '⚛️',
  },
  {
    id: 'neural-link',
    name: 'ニューラルリンク',
    description: '1レベルごとにタイプ効率+150',
    baseCost: 100000000,
    costMultiplier: 2.0,
    bonusPerLevel: 150,
    icon: '🧠',
  },
]
