import type { WordEntry } from '../types/game'

export const WORD_LIST: WordEntry[] = [
  // あいさつ・日常
  { display: 'ありがとうございます', reading: 'ありがとうございます' },
  { display: 'おはようございます', reading: 'おはようございます' },
  { display: 'こんにちは', reading: 'こんにちは' },
  { display: 'こんばんは', reading: 'こんばんは' },
  { display: 'お疲れ様です', reading: 'おつかれさまです' },
  { display: 'よろしくお願いします', reading: 'よろしくおねがいします' },
  { display: 'お先に失礼します', reading: 'おさきにしつれいします' },
  { display: 'いただきます', reading: 'いただきます' },
  { display: 'ごちそうさまでした', reading: 'ごちそうさまでした' },
  { display: 'おやすみなさい', reading: 'おやすみなさい' },
  { display: 'いってきます', reading: 'いってきます' },
  { display: 'ただいま', reading: 'ただいま' },
  { display: 'すみません', reading: 'すみません' },
  { display: 'お元気ですか', reading: 'おげんきですか' },
  { display: 'お世話になっております', reading: 'おせわになっております' },
  { display: 'かしこまりました', reading: 'かしこまりました' },
  { display: 'お待たせしました', reading: 'おまたせしました' },

  // IT・プログラミング基礎
  { display: 'プログラミング', reading: 'ぷろぐらみんぐ' },
  { display: 'エンジニア', reading: 'えんじにあ' },
  { display: 'タイピング', reading: 'たいぴんぐ' },
  { display: 'キーボード', reading: 'きーぼーど' },
  { display: 'コンピューター', reading: 'こんぴゅーたー' },
  { display: 'データベース', reading: 'でーたべーす' },
  { display: 'アルゴリズム', reading: 'あるごりずむ' },
  { display: 'インターネット', reading: 'いんたーねっと' },
  { display: 'ソフトウェア', reading: 'そふとうぇあ' },
  { display: 'アプリケーション', reading: 'あぷりけーしょん' },
  { display: 'オペレーティングシステム', reading: 'おぺれーてぃんぐしすてむ' },
  { display: 'プロトコル', reading: 'ぷろとこる' },
  { display: 'ネットワーク', reading: 'ねっとわーく' },
  { display: 'サーバー', reading: 'さーばー' },
  { display: 'クラウド', reading: 'くらうど' },
  { display: 'ストレージ', reading: 'すとれーじ' },
  { display: 'メモリ', reading: 'めもり' },
  { display: 'プロセッサ', reading: 'ぷろせっさ' },
  { display: 'インターフェース', reading: 'いんたーふぇーす' },
  { display: 'ミドルウェア', reading: 'みどるうぇあ' },

  // 開発用語
  { display: 'プルリクエスト', reading: 'ぷるりくえすと' },
  { display: 'コードレビュー', reading: 'こーどれびゅー' },
  { display: 'デプロイ', reading: 'でぷろい' },
  { display: 'リファクタリング', reading: 'りふぁくたりんぐ' },
  { display: 'フレームワーク', reading: 'ふれーむわーく' },
  { display: 'コンポーネント', reading: 'こんぽーねんと' },
  { display: 'マージコンフリクト', reading: 'まーじこんふりくと' },
  { display: 'テストケース', reading: 'てすとけーす' },
  { display: 'バグ修正', reading: 'ばぐしゅうせい' },
  { display: 'コミットメッセージ', reading: 'こみっとめっせーじ' },
  { display: 'ブランチ', reading: 'ぶらんち' },
  { display: 'ターミナル', reading: 'たーみなる' },
  { display: 'スクリプト', reading: 'すくりぷと' },
  { display: 'ライブラリ', reading: 'らいぶらり' },
  { display: 'リポジトリ', reading: 'りぽじとり' },
  { display: 'コンテナ', reading: 'こんてな' },
  { display: 'パイプライン', reading: 'ぱいぷらいん' },
  { display: 'ビルド', reading: 'びるど' },
  { display: 'コンパイラ', reading: 'こんぱいら' },
  { display: 'デバッグ', reading: 'でばっぐ' },
  { display: 'ログ', reading: 'ろぐ' },
  { display: 'エラーハンドリング', reading: 'えらーはんどりんぐ' },
  { display: '例外処理', reading: 'れいがいしょり' },
  { display: '環境変数', reading: 'かんきょうへんすう' },
  { display: '依存関係', reading: 'いぞんかんけい' },
  { display: '設計書', reading: 'せっけいしょ' },
  { display: '要件定義', reading: 'ようけんていぎ' },
  { display: '技術的負債', reading: 'ぎじゅつてきふさい' },

  // アーキテクチャ・インフラ
  { display: 'バックエンド', reading: 'ばっくえんど' },
  { display: 'フロントエンド', reading: 'ふろんとえんど' },
  { display: 'サーバーレス', reading: 'さーばーれす' },
  { display: 'マイクロサービス', reading: 'まいくろさーびす' },
  { display: 'アーキテクチャ', reading: 'あーきてくちゃ' },
  { display: 'ドキュメント', reading: 'どきゅめんと' },
  { display: 'パフォーマンス', reading: 'ぱふぉーまんす' },
  { display: 'セキュリティ', reading: 'せきゅりてぃ' },
  { display: 'アクセシビリティ', reading: 'あくせしびりてぃ' },
  { display: 'レスポンシブ', reading: 'れすぽんしぶ' },
  { display: 'スケーラビリティ', reading: 'すけーらびりてぃ' },
  { display: 'ロードバランサー', reading: 'ろーどばらんさー' },
  { display: 'キャッシュ', reading: 'きゃっしゅ' },
  { display: 'レプリケーション', reading: 'れぷりけーしょん' },
  { display: 'モニタリング', reading: 'もにたりんぐ' },
  { display: 'オーケストレーション', reading: 'おーけすとれーしょん' },
  { display: 'インフラストラクチャ', reading: 'いんふらすとらくちゃ' },

  // ビジネス・プロジェクト
  { display: 'ミーティング', reading: 'みーてぃんぐ' },
  { display: 'スプリント', reading: 'すぷりんと' },
  { display: 'プロジェクト', reading: 'ぷろじぇくと' },
  { display: 'スケジュール', reading: 'すけじゅーる' },
  { display: 'マネジメント', reading: 'まねじめんと' },
  { display: 'プレゼンテーション', reading: 'ぷれぜんてーしょん' },
  { display: 'フィードバック', reading: 'ふぃーどばっく' },
  { display: 'コミュニケーション', reading: 'こみゅにけーしょん' },
  { display: 'ブレインストーミング', reading: 'ぶれいんすとーみんぐ' },
  { display: 'タスク管理', reading: 'たすくかんり' },
  { display: '進捗報告', reading: 'しんちょくほうこく' },
  { display: '見積もり', reading: 'みつもり' },
  { display: '納品', reading: 'のうひん' },
  { display: '仕様変更', reading: 'しようへんこう' },
  { display: '議事録', reading: 'ぎじろく' },
  { display: '優先順位', reading: 'ゆうせんじゅんい' },
  { display: '工数見積もり', reading: 'こうすうみつもり' },
  { display: 'レトロスペクティブ', reading: 'れとろすぺくてぃぶ' },

  // プログラミング言語・技術名
  { display: 'タイプスクリプト', reading: 'たいぷすくりぷと' },
  { display: 'ジャバスクリプト', reading: 'じゃばすくりぷと' },
  { display: 'パイソン', reading: 'ぱいそん' },
  { display: 'リアクト', reading: 'りあくと' },
  { display: 'ドッカー', reading: 'どっかー' },
  { display: 'クバネティス', reading: 'くばねてぃす' },
  { display: 'テラフォーム', reading: 'てらふぉーむ' },
  { display: 'グラフキューエル', reading: 'ぐらふきゅーえる' },

  // エンジニアの日常フレーズ
  { display: '動くけど汚い', reading: 'うごくけどきたない' },
  { display: '本番環境で確認', reading: 'ほんばんかんきょうでかくにん' },
  { display: 'それは仕様です', reading: 'それはしようです' },
  { display: '再現できません', reading: 'さいげんできません' },
  { display: 'レビューお願いします', reading: 'れびゅーおねがいします' },
  { display: '原因を調査中です', reading: 'げんいんをちょうさちゅうです' },
  { display: '今日中に対応します', reading: 'きょうじゅうにたいおうします' },
  { display: '確認しました', reading: 'かくにんしました' },
  { display: '修正しました', reading: 'しゅうせいしました' },
  { display: '承知しました', reading: 'しょうちしました' },
  { display: '共有ありがとうございます', reading: 'きょうゆうありがとうございます' },
  { display: 'マージしていいですか', reading: 'まーじしていいですか' },

  // 短い単語（テンポよく）
  { display: '実装', reading: 'じっそう' },
  { display: '開発', reading: 'かいはつ' },
  { display: '設計', reading: 'せっけい' },
  { display: '運用', reading: 'うんよう' },
  { display: '保守', reading: 'ほしゅ' },
  { display: '障害', reading: 'しょうがい' },
  { display: '復旧', reading: 'ふっきゅう' },
  { display: '権限', reading: 'けんげん' },
  { display: '認証', reading: 'にんしょう' },
  { display: '暗号化', reading: 'あんごうか' },
  { display: '最適化', reading: 'さいてきか' },
  { display: '自動化', reading: 'じどうか' },
  { display: '可視化', reading: 'かしか' },
  { display: '初期化', reading: 'しょきか' },
  { display: '正規化', reading: 'せいきか' },
  { display: '並列処理', reading: 'へいれつしょり' },
  { display: '非同期', reading: 'ひどうき' },
  { display: '冗長化', reading: 'じょうちょうか' },
]
